### ISSUE TITLE
Unusable with JVM 21

### ISSUE THREAD

**Issue by sgammon** [stytchauth/stytch-android#188]
We build against JVM 21 on Android, but:

```
* What went wrong:
Execution failed for task ':sdk:kaptGenerateStubsDebugKotlin'.
> Error while evaluating property 'compilerOptions.jvmTarget' of task ':sdk:kaptGenerateStubsDebugKotlin'.
   > Failed to calculate the value of property 'jvmTarget'.
      > Unknown Kotlin JVM target: 21

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.
```

**Comment by jhaven-stytch** [comment]
Looking into this, thanks!

**Comment by jhaven-stytch** [comment]
Hey @sgammon,

Can you explain how/where you're seeing this issue? Are you trying to integrate Stytch in your existing codebase, or are you attempting to update the demo apps in this repository to use JVM 21?

The supported JVM targets are a function of the version of Kotlin being used by a project, and JVM 21 isn't supported until (maybe, I see conflicting info online) 1.9.20 or (for sure) 2.0.0. The projects in this repository are currently using Kotlin 1.8.22 (though we have a branch to upgrade to 2.0.0 [here](#183)). So, that said, you won't be able to change the JVM target in the apps in this repository, as the version of Kotlin used does not support it.

However, if you have an existing project setup with a version of Kotlin that _does_ support JVM 21 (ie: 2.0.0), you should have no problems. I just spun up a demo app in Android Studio, upgraded everything to the latest (to support JVM 21), and the most recent version of our SDK artifact works without issue. If you are seeing something different, I would love to know!

**Comment by jhaven-stytch** [comment]
I went ahead and just pushed up an updated branch of our previously mentioned example app using K2 and the latest gradle, AGP, and java versions that you can check out: https://github.com/stytchauth/stytch-android-example/pull/4

**Comment by sgammon** [comment]
@jhaven-stytch We are currently using Kotlin 2.0.0, and building against JVM 22 actually, but with a JVM 21 target set for bytecode. I'll try and see where this failed for us

**Comment by jhaven-stytch** [comment]
Hey @sgammon just wanted to check in and see if you had any luck :)
